---
- import_role:
    name: geerlingguy.apache
- import_role:
    name: pbench-server-firewall
- import_role:
    name: pbench-server-install-config-file
- import_role:
    name: pbench-server-vars
- import_role:
    name: pbench-server-user
- import_role:
    name: pbench-server-activate-create-crontab
- import_role:
    name: pbench-server-activate-setup-results-host-info
- import_role:
    name: pbench-server-activate-create-results-dir-structure
- import_role:
    name: pbench-server-activate-httpd-setup-restart
- import_role:
    name: pbench-server-add-commit-id
- import_role:
    name: pbench-server-change-ownership
- import_role:
    name: pbench-server-systemd-service
