dist: bionic
jobs:
  include:
    - stage: "Agent Unit Tests"
      name: "agent-unit-tests"
      language: python
      python:
        - "3.6"
      before_install:
        - sudo apt-get update
        - command -v sleep
      install:
        # Perl JSON and JSON-XS required
        - sudo apt-get install libjson-perl libjson-xs-perl
      script: ./agent/run-unittests

    - stage: "Server Unit Tests"
      name: "server-unit-tests"
      language: python
      python:
        - "3.6"
      env:
        - PBENCH_UNITTEST_SERVER_MODE=serial
      before_install:
        - sudo apt-get update
      install:
        - pip install elasticsearch sh boto3
      script: ./server/bin/unittests
