---
fedoraproject_username: ndokos
pbench_repo_url_prefix: https://copr-be.cloud.fedoraproject.org/results/{{ fedoraproject_username }}

repos:
  - tag: pbench
    user: "{{ fedoraproject_username }}"
    baseurl: "{{ pbench_repo_url_prefix }}/pbench/{{ distrodir }}"
    gpgkey: "{{ pbench_repo_url_prefix }}/pbench/pubkey.gpg"
    gpgcheck: 1
    enabled: 1

